# Generated by Django 4.2 on 2026-04-27 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_courier',
            field=models.BooleanField(default=False, verbose_name='Курьер'),
        ),
    ]
