# Generated by Django 5.2.7 on 2025-10-10 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_saleevent'),
        ('products', '0006_alter_brand_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('processing', 'В обработке'), ('paid', 'Оплачен'), ('shipped', 'Отправлен'), ('delivered', 'Доставлен')], default='processing', max_length=20, verbose_name='Статус заказа'),
        ),
        migrations.AlterField(
            model_name='saleevent',
            name='action',
            field=models.CharField(choices=[('purchase', 'Purchase'), ('refund', 'Refund')], max_length=50, verbose_name='Тип события'),
        ),
        migrations.AlterField(
            model_name='saleevent',
            name='order_id',
            field=models.PositiveIntegerField(verbose_name='ID заказа'),
        ),
        migrations.AlterField(
            model_name='saleevent',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='saleevent',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='saleevent',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время события'),
        ),
        migrations.AlterField(
            model_name='saleevent',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма'),
        ),
    ]
