# Generated by Django 5.2.7 on 2025-10-10 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_status_alter_saleevent_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='price_at_purchase',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Цена на момент покупки'),
            preserve_default=False,
        ),
    ]
