# Generated by Django 5.2.7 on 2025-10-10 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_orderitem_price_at_purchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleevent',
            name='order_id',
        ),
        migrations.AddField(
            model_name='saleevent',
            name='order',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='Заказ'),
            preserve_default=False,
        ),
    ]
