# Generated by Django 5.2.7 on 2025-10-10 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='discount_applied',
            field=models.BooleanField(default=False, verbose_name='Скидка применена'),
        ),
    ]
