# Generated by Django 5.2.7 on 2026-04-11 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_cartitem_unique_user_product_cart_item'),
        ('products', '0010_alter_product_options_alter_review_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='saleevent',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Событие продажи', 'verbose_name_plural': 'События продаж'},
        ),
        migrations.AddField(
            model_name='order',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата отмены'),
        ),
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий к заказу'),
        ),
        migrations.AddField(
            model_name='order',
            name='courier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courier_orders', to=settings.AUTH_USER_MODEL, verbose_name='Курьер'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата оплаты'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Картой'), ('cash', 'Наличными')], default='card', max_length=20, verbose_name='Способ оплаты'),
        ),
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=11, verbose_name='Телефон получателя'),
        ),
        migrations.AddField(
            model_name='order',
            name='recipient_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Имя получателя'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipped_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата отправки'),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_note',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Комментарий по статусу'),
        ),
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Название товара на момент покупки'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='products.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('standard', 'Обычная доставка'), ('express', 'Экспресс доставка')], default='standard', max_length=50, verbose_name='Способ доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='products.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='saleevent',
            name='action',
            field=models.CharField(choices=[('purchase', 'Покупка'), ('refund', 'Возврат')], max_length=50, verbose_name='Тип события'),
        ),
        migrations.AlterField(
            model_name='saleevent',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_events', to='orders.order', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='saleevent',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_events', to='products.product', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='saleevent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('processing', 'В обработке'), ('paid', 'Оплачен'), ('shipped', 'Отправлен'), ('delivered', 'Доставлен'), ('cancelled', 'Отменен')], max_length=20, verbose_name='Статус')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changed_order_statuses', to=settings.AUTH_USER_MODEL, verbose_name='Кем изменено')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='orders.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'История статуса заказа',
                'verbose_name_plural': 'История статусов заказов',
                'ordering': ['-created_at'],
            },
        ),
    ]
