# Generated by Django 5.2.7 on 2025-10-10 09:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_brand_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название скидки')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('discount_percent', models.PositiveIntegerField(default=0, verbose_name='Процент скидки')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата начала')),
                ('end_date', models.DateTimeField(verbose_name='Дата окончания')),
                ('active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Скидка',
                'verbose_name_plural': 'Скидки',
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название акции')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание акции')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата начала')),
                ('end_date', models.DateTimeField(verbose_name='Дата окончания')),
                ('active', models.BooleanField(default=True, verbose_name='Активно')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='products.discount', verbose_name='Скидка')),
                ('products', models.ManyToManyField(related_name='promotions_for_product', to='products.product', verbose_name='Товары в акции')),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акции',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='promotions',
            field=models.ManyToManyField(blank=True, related_name='products_in_promotion', to='products.promotion', verbose_name='Акции'),
        ),
    ]
