# Generated by Django 5.2.7 on 2025-10-10 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_discount_promotion_product_promotions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название скидки')),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Процент скидки')),
                ('start_date', models.DateTimeField(verbose_name='Дата начала скидки')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания скидки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Скидка',
                'verbose_name_plural': 'Скидки',
            },
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='products',
        ),
        migrations.RemoveField(
            model_name='product',
            name='promotions',
        ),
        migrations.AddField(
            model_name='product',
            name='sales',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.sale', verbose_name='Скидки'),
        ),
        migrations.DeleteModel(
            name='Discount',
        ),
        migrations.DeleteModel(
            name='Promotion',
        ),
    ]
