# Generated by Django 5.2.7 on 2026-02-18 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_sale_remove_promotion_discount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='memory',
        ),
        migrations.RemoveField(
            model_name='product',
            name='processor',
        ),
        migrations.RemoveField(
            model_name='product',
            name='screen_size',
        ),
        migrations.AddField(
            model_name='product',
            name='additional_info',
            field=models.TextField(blank=True, verbose_name='Дополнительная информация'),
        ),
    ]
