"""
Django settings for electronics_store project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-l+yml%8lszhiueg9dumi+6o6v%p)-h2p1+8kr0!5n+4e$3llpf'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',  # Для работы allauth

    # Приложения для проекта
    'accounts',
    'products',
    'orders',
    'blog',
    'promotions',

    # Дополнительные пакеты
    'allauth',  # Для регистрации и аутентификации
    'crispy_forms',  # Для удобного рендеринга форм с Bootstrap
    'crispy_bootstrap5',  # Для использования Bootstrap 5 с crispy_forms
    'widget_tweaks',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    
]

ROOT_URLCONF = 'electronics_store.urls'
import os
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'electronics_store.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

# Папки для статических файлов (для разработки)
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'), BASE_DIR / 'static,static/css',
]

# Статические файлы для продакшн-режима
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  

# Медиа файлы (для загрузки изображений)
MEDIA_URL = '/media/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIAFILES_DIRS = [os.path.join(BASE_DIR, 'media')]


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',  # Стандартный бекенд Django
    'allauth.account.auth_backends.AuthenticationBackend',  # Если используете django-allauth
)

# Указываем модель пользователя
AUTH_USER_MODEL = 'accounts.CustomUser'

# Настройки для работы с email
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'  # Для разработки

# Настройки allauth
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'  # Проверка email обязательна
ACCOUNT_EMAIL_REQUIRED = True  # Требуется email
ACCOUNT_AUTHENTICATED_REDIRECT_URL = '/'  # Куда отправлять после входа
ACCOUNT_LOGOUT_REDIRECT_URL = '/'  # Куда отправлять после выхода

# Дополнительные настройки для allauth
ACCOUNT_FORMS = {
    'signup': 'accounts.forms.CustomUserCreationForm',  # Пользовательская форма регистрации
}
CRISPY_ALLOWED_TEMPLATE_PACKS = 'bootstrap5'
CRISPY_TEMPLATE_PACK = 'bootstrap5'
LOGIN_REDIRECT_URL = '/accounts/profile/'  # куда пользователь идет после успешного входа
LOGOUT_REDIRECT_URL = '/'  # куда пользователь идет после выхода