"""
Django settings for electronics_store project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
from dotenv import load_dotenv  


load_dotenv()
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY")  

if os.environ.get("DEBUG") == "False":
    DEBUG = False
else:
    DEBUG = True
# SECURITY WARNING: don't run with debug turned on in production!
SESSION_COOKIE_SECURE = True  
CSRF_COOKIE_SECURE = True
ALLOWED_HOSTS = ['localhost', 'qweasd22.pythonanywhere.com']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',  # Для работы allauth
    
    # Приложения для проекта
    'accounts',
    'products',
    'orders',
    'news',
    'promotions',
    'blog',

    # Дополнительные пакеты
    'allauth',  # Для регистрации и аутентификации
    'crispy_forms',  # Для удобного рендеринга форм с Bootstrap
    'crispy_bootstrap5',  # Для использования Bootstrap 5 с crispy_forms
    'widget_tweaks',
    'django'
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    
]

ROOT_URLCONF = 'electronics_store.urls'
import os
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'electronics_store.wsgi.application'
SITE_ID = 1

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {  
    "default": {  
        "ENGINE": "django.db.backends.mysql",  
        "NAME": os.getenv("MYSQL_DBNAME"),  
        "USER": os.getenv("MYSQL_USER"),  
        "PASSWORD": os.getenv("MYSQL_PASSWORD"),  
        "HOST": os.getenv("MYSQL_HOST"),  
        "OPTIONS": {  
            "init_command": "SET NAMES 'utf8mb4';SET sql_mode = 'STRICT_TRANS_TABLES'",  
            "charset": "utf8mb4",  
        },  
    }  
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

# Папки для статических файлов (для разработки)
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'), BASE_DIR / 'static,static/css',
]

# Статические файлы для продакшн-режима
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  

# Медиа файлы (для загрузки изображений)
MEDIA_URL = '/media/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIAFILES_DIRS = [os.path.join(BASE_DIR, 'media')]


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',  # Стандартный бекенд Django
    'allauth.account.auth_backends.AuthenticationBackend',  # Если используете django-allauth
)
LANGUAGE_CODE = 'ru'
USE_I18N = True
USE_L10N = True
USE_TZ = True
# Указываем модель пользователя
AUTH_USER_MODEL = 'accounts.CustomUser'

# Настройки для работы с email
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'  # Для разработки

# Настройки allauth
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'  # Проверка email обязательна
ACCOUNT_EMAIL_REQUIRED = True  # Требуется email
ACCOUNT_AUTHENTICATED_REDIRECT_URL = '/'  # Куда отправлять после входа
ACCOUNT_LOGOUT_REDIRECT_URL = '/'  # Куда отправлять после выхода

# Дополнительные настройки для allauth
ACCOUNT_FORMS = {
    'signup': 'accounts.forms.CustomUserCreationForm',  # Пользовательская форма регистрации
}
CRISPY_ALLOWED_TEMPLATE_PACKS = 'bootstrap5'
CRISPY_TEMPLATE_PACK = 'bootstrap5'
LOGIN_REDIRECT_URL = '/accounts/profile/'  # куда пользователь идет после успешного входа
LOGOUT_REDIRECT_URL = '/'  # куда пользователь идет после выхода

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'electronik223213@gmail.com'  # Ваш email
EMAIL_HOST_PASSWORD = 'avtn lasc oijr aftb'  # Ваш пароль или app password
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
ADMIN_EMAIL = 'electronik223213@gmail.com'  # Email администратора для получения уведомлений